### PR TITLE
Develop design6

### PR DESCRIPTION
**Pull request by iqbalutomo**
I'm trying to develop with React and Tailwind, I apologize if the design isn't as perfect as the original prototype.

### CODE REVIEW

**Comment by iqbalutomo** [comment]
It's okay, happily waiting

**Comment by rishikeshreddyakkireddy** [comment]
Hey nice work @iqbalutomo, except for the font size of the header.

**Comment by iqbalutomo** [comment]
Thank you, but for a 27 inch screen it's good, I don't give a specific size for other screen sizes, ok I'm trying to fix it

**Comment by iqbalutomo** [comment]
Please check

**Comment by rishikeshreddyakkireddy** [comment]
Everything looks fine now, and awesome work brother.

**Comment by iqbalutomo** [comment]
Thank you very much and I also thank you for the permission that has been given to take part in this challenge, will the merger be done?

**Comment by rishikeshreddyakkireddy** [comment]
Yeah, I will merge it, this has to be merged ;)

**Comment by iqbalutomo** [comment]
Once again, thank you so much👏

**Comment by rishikeshreddyakkireddy** [comment]
Welcome brother and keep contributing to my repo @iqbalutomo. :)

**Comment by rishikeshreddyakkireddy** [comment]
@iqbalutomo And do have any suggestions for me brother, I would love to hear from you.

**Comment by iqbalutomo** [comment]
Okay, my advice might be to give logo and font assets to make slicing easier and the results might be more perfect🙌

**Comment by nikhilreddydev** [comment]
@iqbalutomo yeah, we are working on reducing the friction to provide best assets.

**Pull request merged**
