### PR TITLE
implemented design 57

### PR DESCRIPTION
**Pull request by m3gh4l4**
I implemented design 57.
Made some changes in the design as per my taste. 
 Here is how it looks.

Screenshot (880)

### CODE REVIEW

**Comment by rishikeshreddyakkireddy** [comment]
@m3gh4l4 I would suggest aligning black and white boxes properly, and also you need to increase the size of those boxes

**Comment by m3gh4l4** [comment]
Cool. I will do the changes. 

And yes I am participating.

**Comment by m3gh4l4** [comment]
Hey!! You have not yet accepted my PR. Do you want me to do any other changes?

**Comment by rishikeshreddyakkireddy** [comment]
@m3gh4l4 this is completely good but I have merged the @hiddenlucas code, cause it was a bit more accurate in this, keep contributing :)

**Pull request closed without merging**
