### PR TITLE
implemented design43

### PR DESCRIPTION
**Pull request by noob0412**
recodio

### CODE REVIEW

**Comment by noob0412** [comment]
Please merge

**Comment by rishikeshreddyakkireddy** [comment]
Awesome work brother :)

**Comment by noob0412** [comment]
Thank you @rishikeshreddyakkireddy please assign me some of the more issues

**Comment by noob0412** [comment]
Sorry @rishikeshreddyakkireddy there is no such design5 in the issue section can you please point it out to me, it will be very helpful for me

**Pull request merged**
